### ISSUE TITLE
A suggestion

### ISSUE THREAD

**Issue by pureformat** [torvalds/test-tlb#1]
Nice pet project, this, Linus.

However, how about a pet project to solve the fucking binary distribution problem on Linux? The "year of the Linux desktop" will not happen until *you* solve this.

In return, I will pet your cat, bring you coffee and recite LKML for two weeks.

**Comment by ericcurtin** [comment]
Have a read about the development of Snappy or Flatpack. You might find it interesting. They both aim to solve this problem, even better, maybe try and get involved in one of these projects if you think you can help.

**Comment by pureformat** [comment]
Cool
